name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them'
inputs:
  caching:
    description: 'Cache dependency flag'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    # caching dependencies for npm packages
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        # creates a new hash key if lock file is updated
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash