name: Test Project
on: push
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
         - name: Get code
           uses: actions/checkout@v3
         - name: Install NodeJS
           uses: actions/setup-node@v3
           with:
              node-version: 18
         - name: Install dependencies
           run: npm ci
         - name: Run Build
           run: npm build
         - name: Upload artifact
           uses: actions/upload-artifact@v3
           with:
             name: dist-files
             path: dist
             # path: |
             #   dist
             #   package.json
    deploy:
      needs: build
      uses: ./.github/workflows/reusuable.yml
      with:
        artifact-name: dist-files